---
title: "NBA Jackknife Resampling"
author: "Hubert Luo"
date: "February 18, 2018"
output: github_document
---

##Jackknife Resampling: Points

```{r}
dat <- read.csv('nba2017-players.csv', stringsAsFactors = FALSE)
dat_points <- na.omit(dat$points)
n = 100 #Sample size

#Take simple random sample of size n
srs = sample(dat_points,n)

#Remove 1 observation with jackknife
jackknifeSamples = numeric()
for (i in 1:n) {
  jackknifeSamples = c(jackknifeSamples, mean(srs[-i]))
}

#Alternatively, we can use the jackknife function in the bootstrap package
library(bootstrap)
jackknife(srs, theta = mean) #Returns a list consisting of resampling standard error, bias, and values

#Remove 2 observations with jackknife
jackknifeSamples2 = numeric()
for (i in 1:n) {
  for (j in (i+1):n) {
    jackknifeSamples2 = c(jackknifeSamples2, mean(srs[-c(i,j)]))
  }
}
```

##Compare Samples from Jackknfie Resampling
```{r}
plot(jackknifeSamples, xlab = "Sample", ylab = "Average Points", main = "Samples from Jackknife")
plot(jackknifeSamples2, xlab = "Sample", ylab = "Average Points", main = "Samples from Jackknife with Two Removals")
```

##Compare Accuracies

```{r}
mean(dat_points) #Population 
mean(srs) #Simple Random Sample
mean(jackknifeSamples) #Jackknife Resampling with 1 removal - note that this will be very close to the population parameter (Bias = 0) 
mean(jackknifeSamples2) 

sd(dat_points)
sd(srs)
sd(jackknifeSamples)
sd(jackknifeSamples2)
```