---
title: "NBA Bootstrap Resampling"
author: "Hubert Luo"
date: "February 17, 2018"
output: github_document
---

##Boostrap Resampling: Points

```{r}
dat <- read.csv('nba2017-players.csv', stringsAsFactors = FALSE)
dat_points <- na.omit(dat$points)
n = 100 #Sample size

#Take simple random sample of size n
srs = sample(dat_points,n)

#Take boostrap sample by repeating each entry number of times needed to approximate population
bootstrapSamples = numeric()
numRepeats = round(length(dat_points)/n)
for (i in 1:n){
  bootstrapSamples = c(bootstrapSamples, rep(srs[i],numRepeats))
}
```

##Compare Accuracies

```{r}
mean(dat_points) #Population 
mean(srs) #Simple Random Sample
mean(bootstrapSamples) #Bootstrap Resampling

sd(dat_points)
sd(srs)
sd(bootstrapSamples)
```

##Simple Random Sampling: All Parameters

We will take a sample of 100 players and try to estimate population parameters (for all 441 NBA players) from their sample statistics.

```{r}
numeric_dat <- dat[, -c(1,2,3,8)] #Keep the numeric variables to calculate population parameters
pop_params <- numeric() #Create empty vector to store population parameters
for (sample_var in 1:(ncol(numeric_dat))){
  pop_params = c(pop_params,mean(numeric_dat[[sample_var]])) #Append population parameters of each variable to previously created vector
}
names(pop_params) <- colnames(numeric_dat) #Label what each parameter is
pop_params

sample_dat <- dat[sample(nrow(dat),100),] #Take sample of 100 players without replacement

numeric_sample_dat <- sample_dat[, -c(1,2,3,8)] #Keep the numeric variables to calculate sample statistics
x_bars <- numeric() #Create empty vector to store sample statistics
for (sample_var in 1:(ncol(numeric_sample_dat))){
  x_bars = c(x_bars,mean(numeric_sample_dat[[sample_var]])) #Append sample statistic of each variable to previously created vector
}
names(x_bars) <- colnames(numeric_sample_dat) #Label what each statistic is 
x_bars

#Calculate standard errors

N = nrow(dat) #Population size
n = nrow(sample_dat) #Sample size

s_xbars = numeric() #create empty vector to store SE's
for (sample_var in 1:(ncol(numeric_sample_dat))){
  s_xbars = c(s_xbars,sqrt(var(numeric_sample_dat[[sample_var]])/(n-1)*((N-n)/N))) #Append SE of each variable to previously created vector
}
names(s_xbars) <- colnames(numeric_sample_dat) #Label what each statistic is 
s_xbars

#Calculate bounds for 95% Confidence Intervals
uBounds = s_xbars + 1.96*s_xbars
uBounds

lBounds = s_xbars - 1.96*s_xbars
lBounds
```

##Bootstrap 

Now, we will take our sample from earlier and apply the boostrap.

```{r}
sample_factor = round(nrow(dat)/100) #Calculate how many times we need to repeat each observation
bootstrap_dat <- sample_dat[rep(seq_len(nrow(sample_dat)),each = sample_factor),] #Repeats each row sample_factor number of times
numeric_bootstrap <- bootstrap_dat[, -c(1,2,3,8)] #Keep the numeric variables to calculate sample statistics
bootstrap_x_bars <- numeric() #Create empty vector to store sample statistics
for (sample_var in 1:(ncol(numeric_bootstrap))){
  bootstrap_x_bars = c(bootstrap_x_bars,mean(numeric_bootstrap[[sample_var]])) #Append sample statistic of each variable to previously created vector
}
names(bootstrap_x_bars) <- colnames(numeric_bootstrap) #Label what each statistic is 
bootstrap_x_bars

#Now, calculate standard errors from bootstrap

n = nrow(bootstrap_dat) #Sample size has changed!

bootstrap_s_xbars = numeric() #create empty vector to store SE's
for (sample_var in 1:(ncol(numeric_bootstrap))){
  bootstrap_s_xbars = c(bootstrap_s_xbars,sqrt(var(numeric_bootstrap[[sample_var]])/(n-1)*((N-n)/N))) #Append SE of each variable to previously created vector
}
names(bootstrap_s_xbars) <- colnames(numeric_bootstrap) #Label what each statistic is 
bootstrap_s_xbars

#Calculate bounds for 95% Confidence Intervals
bootstrap_uBounds = bootstrap_s_xbars + 1.96*bootstrap_s_xbars
bootstrap_uBounds

bootstrap_lBounds = bootstrap_s_xbars - 1.96*bootstrap_s_xbars
bootstrap_lBounds
```