---
title: "NBA Principal Component Analysis"
author: "Hubert Luo"
date: "February 20, 2018"
output: html_document
---

##Run PCA and List Results

```{r}
dat <- read.csv('nba2017-players.csv', stringsAsFactors = FALSE)
quant_dat = dat[,-c(1:3,8)] #Only keep quantiative data for pca (numeric/integer data type)
pca_nba <- prcomp(quant_dat, scale. = TRUE)

eigenvalues <- pca_nba$sdev^2  #Variance of the Principal Component (PC's) is equal to the eigenvalue of the PC
eigenvaluesdf <- data.frame(1:11, eigenvalues) #Create dataframe of eigenvalues with column for each PC
names(eigenvaluesdf)[1] <- "PC"
barplot(eigenvaluesdf$eigenvalues, names.arg = eigenvaluesdf$PC, xlab = "Principal Component", ylab = "Eigenvalue", main = "Eigenvalue of Each PC", col = c("blue","gold"))

loadings <- pca_nba$rotation #Weights of each PC
round(loadings,3)
```

##Proportion of Variance

```{r}
#Add columns to evaluate variance of PC's in terms of percentages and cumulative percentages
eigenvaluesdf[,"Percentage"] <- round(eigenvaluesdf$eigenvalues/sum(eigenvaluesdf$eigenvalues)*100,2)
eigenvaluesdf[,"Cumulative_%"] <- cumsum(eigenvaluesdf$Percentage)
eigenvaluesdf

barplot(eigenvaluesdf$Percentage,names.arg = eigenvaluesdf$PC, main = "Bar Chart of Eigenvalues", xlab = "Principal Component", ylab = "Eigenvalue")
```

Note that almost all of the variability (83%) is captured by the first three principal components. Almost half of the variability (47%) is captured in the first principal component.